Update index.html
projecthorus/radiosonde_auto_rx pull request #358
Opened 2021-01-12 12:15 UTC by Piter-NS

Support for radiosondy.info when set to disable sending data to Habitat. #357

2021-01-13 09:19 UTC, snh requested changes
Thanks for the contribution @Piter-NS ❤️ 

It'd be worth making the link conditional on `aprs_enabled` being `True` and `aprs_server` being`radiosondy.info`.

2021-01-14 09:15 UTC, darksidelemm commented
+1 on above. The extra conditions would be good in case users are pushing data directly into APRS-IS.

2021-01-15 20:23 UTC, Piter-NS commented
What is the APRS-IS server address?  After setting up the APRS-IS server, I could make the link go to aprs.fi maps.

2021-01-15 21:07 UTC, darksidelemm commented
Good idea to use an aprs.fi link if radiosondy.info is not used (and Habitat is disabled... which i kind of hope is never the case by the way...)
Unfortunately there's a lot of them, and most people would be using one in their country. I'd say if the aprs_server value is anything other than radiosondy.info, then use aprs.fi maps.

2021-01-18 06:58 UTC, merged

2021-01-18 06:59 UTC, darksidelemm commented
Thanks for making those changes, all good!